# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b145d6e965dd46da1e63d7938469a53b62fee35f18785b8f5e115fefc0f9306680222e3e0e1ad845290122b334e54c412f5f2917893667e9849266e5768194b3

test:
  secret_key_base: 7bdc7d96ea2a61a8e284e5c720c3cd0224051e52c3105f5c750b7b167d96643d54bf4f44f6be79a019c6fc2b7bbc6e201ba7c436b1ab48306acc703ca74d8d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
